In [1]:
import numpy as np
a = np.zeros((3,3,3))
print(a[:, 1, :].shape)

(3, 3)


In [3]:
for i in range(4 - 1, -1, -1):
    print(i)

3
2
1
0


In [3]:
W = np.linspace(0, 1, num=5*3).reshape(5, 3)
print(W)

[[0.         0.07142857 0.14285714]
 [0.21428571 0.28571429 0.35714286]
 [0.42857143 0.5        0.57142857]
 [0.64285714 0.71428571 0.78571429]
 [0.85714286 0.92857143 1.        ]]


In [4]:
{'lstm': 4, 'rnn': 1}['rnn']

1

In [5]:
{'lstm': 4, 'rnn': 1}

{'lstm': 4, 'rnn': 1}

In [4]:
import numpy as np
a = np.array([1, 2, 3, 4])
a[None].shape

(1, 4)

In [2]:
for i in range(::5):
    print(i)

SyntaxError: invalid syntax (<ipython-input-2-808a3f4ab8a1>, line 1)

In [2]:
import tensorflow as tf
tensor=tf.constant([1, 2], dtype=tf.float32)
print(tensor[1:2])

SyntaxError: invalid character in identifier (<ipython-input-2-fe09ed28d01b>, line 2)